/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Error
 */
public class ErrorTest {
    private final Error model = new Error();

    /**
     * Model tests for Error
     */
    @Test
    public void testError() {
        // TODO: test Error
    }

    /**
     * Test the property 'code'
     */
    @Test
    public void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'reason'
     */
    @Test
    public void reasonTest() {
        // TODO: test reason
    }

    /**
     * Test the property 'message'
     */
    @Test
    public void messageTest() {
        // TODO: test message
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'referenceError'
     */
    @Test
    public void referenceErrorTest() {
        // TODO: test referenceError
    }

    /**
     * Test the property 'atBaseType'
     */
    @Test
    public void atBaseTypeTest() {
        // TODO: test atBaseType
    }

    /**
     * Test the property 'atSchemaLocation'
     */
    @Test
    public void atSchemaLocationTest() {
        // TODO: test atSchemaLocation
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

}
