/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ProductOffering;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProductOfferingCreateEventPayload
 */
public class ProductOfferingCreateEventPayloadTest {
    private final ProductOfferingCreateEventPayload model = new ProductOfferingCreateEventPayload();

    /**
     * Model tests for ProductOfferingCreateEventPayload
     */
    @Test
    public void testProductOfferingCreateEventPayload() {
        // TODO: test ProductOfferingCreateEventPayload
    }

    /**
     * Test the property 'productOffering'
     */
    @Test
    public void productOfferingTest() {
        // TODO: test productOffering
    }

}
