/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ProductOfferingPrice;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProductOfferingPriceDeleteEventPayload
 */
public class ProductOfferingPriceDeleteEventPayloadTest {
    private final ProductOfferingPriceDeleteEventPayload model = new ProductOfferingPriceDeleteEventPayload();

    /**
     * Model tests for ProductOfferingPriceDeleteEventPayload
     */
    @Test
    public void testProductOfferingPriceDeleteEventPayload() {
        // TODO: test ProductOfferingPriceDeleteEventPayload
    }

    /**
     * Test the property 'productOfferingPrice'
     */
    @Test
    public void productOfferingPriceTest() {
        // TODO: test productOfferingPrice
    }

}
