/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.AgreementRef;
import org.openapitools.client.model.AttachmentRefOrValue;
import org.openapitools.client.model.BundledProductOffering;
import org.openapitools.client.model.CategoryRef;
import org.openapitools.client.model.ChannelRef;
import org.openapitools.client.model.MarketSegmentRef;
import org.openapitools.client.model.PlaceRef;
import org.openapitools.client.model.ProductOfferingPriceRef;
import org.openapitools.client.model.ProductOfferingTerm;
import org.openapitools.client.model.ProductSpecificationCharacteristicValueUse;
import org.openapitools.client.model.ProductSpecificationRef;
import org.openapitools.client.model.ResourceCandidateRef;
import org.openapitools.client.model.SLARef;
import org.openapitools.client.model.ServiceCandidateRef;
import org.openapitools.client.model.TimePeriod;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProductOfferingUpdate
 */
public class ProductOfferingUpdateTest {
    private final ProductOfferingUpdate model = new ProductOfferingUpdate();

    /**
     * Model tests for ProductOfferingUpdate
     */
    @Test
    public void testProductOfferingUpdate() {
        // TODO: test ProductOfferingUpdate
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'isBundle'
     */
    @Test
    public void isBundleTest() {
        // TODO: test isBundle
    }

    /**
     * Test the property 'isSellable'
     */
    @Test
    public void isSellableTest() {
        // TODO: test isSellable
    }

    /**
     * Test the property 'lifecycleStatus'
     */
    @Test
    public void lifecycleStatusTest() {
        // TODO: test lifecycleStatus
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'statusReason'
     */
    @Test
    public void statusReasonTest() {
        // TODO: test statusReason
    }

    /**
     * Test the property 'version'
     */
    @Test
    public void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'agreement'
     */
    @Test
    public void agreementTest() {
        // TODO: test agreement
    }

    /**
     * Test the property 'attachment'
     */
    @Test
    public void attachmentTest() {
        // TODO: test attachment
    }

    /**
     * Test the property 'bundledProductOffering'
     */
    @Test
    public void bundledProductOfferingTest() {
        // TODO: test bundledProductOffering
    }

    /**
     * Test the property 'category'
     */
    @Test
    public void categoryTest() {
        // TODO: test category
    }

    /**
     * Test the property 'channel'
     */
    @Test
    public void channelTest() {
        // TODO: test channel
    }

    /**
     * Test the property 'marketSegment'
     */
    @Test
    public void marketSegmentTest() {
        // TODO: test marketSegment
    }

    /**
     * Test the property 'place'
     */
    @Test
    public void placeTest() {
        // TODO: test place
    }

    /**
     * Test the property 'prodSpecCharValueUse'
     */
    @Test
    public void prodSpecCharValueUseTest() {
        // TODO: test prodSpecCharValueUse
    }

    /**
     * Test the property 'productOfferingPrice'
     */
    @Test
    public void productOfferingPriceTest() {
        // TODO: test productOfferingPrice
    }

    /**
     * Test the property 'productOfferingTerm'
     */
    @Test
    public void productOfferingTermTest() {
        // TODO: test productOfferingTerm
    }

    /**
     * Test the property 'productSpecification'
     */
    @Test
    public void productSpecificationTest() {
        // TODO: test productSpecification
    }

    /**
     * Test the property 'resourceCandidate'
     */
    @Test
    public void resourceCandidateTest() {
        // TODO: test resourceCandidate
    }

    /**
     * Test the property 'serviceCandidate'
     */
    @Test
    public void serviceCandidateTest() {
        // TODO: test serviceCandidate
    }

    /**
     * Test the property 'serviceLevelAgreement'
     */
    @Test
    public void serviceLevelAgreementTest() {
        // TODO: test serviceLevelAgreement
    }

    /**
     * Test the property 'validFor'
     */
    @Test
    public void validForTest() {
        // TODO: test validFor
    }

    /**
     * Test the property 'atBaseType'
     */
    @Test
    public void atBaseTypeTest() {
        // TODO: test atBaseType
    }

    /**
     * Test the property 'atSchemaLocation'
     */
    @Test
    public void atSchemaLocationTest() {
        // TODO: test atSchemaLocation
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

}
