/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.ProductSpecificationCharacteristicRelationship;
import org.openapitools.client.model.ProductSpecificationCharacteristicValue;
import org.openapitools.client.model.TimePeriod;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ProductSpecificationCharacteristic
 */
public class ProductSpecificationCharacteristicTest {
    private final ProductSpecificationCharacteristic model = new ProductSpecificationCharacteristic();

    /**
     * Model tests for ProductSpecificationCharacteristic
     */
    @Test
    public void testProductSpecificationCharacteristic() {
        // TODO: test ProductSpecificationCharacteristic
    }

    /**
     * Test the property 'configurable'
     */
    @Test
    public void configurableTest() {
        // TODO: test configurable
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'extensible'
     */
    @Test
    public void extensibleTest() {
        // TODO: test extensible
    }

    /**
     * Test the property 'isUnique'
     */
    @Test
    public void isUniqueTest() {
        // TODO: test isUnique
    }

    /**
     * Test the property 'maxCardinality'
     */
    @Test
    public void maxCardinalityTest() {
        // TODO: test maxCardinality
    }

    /**
     * Test the property 'minCardinality'
     */
    @Test
    public void minCardinalityTest() {
        // TODO: test minCardinality
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'regex'
     */
    @Test
    public void regexTest() {
        // TODO: test regex
    }

    /**
     * Test the property 'valueType'
     */
    @Test
    public void valueTypeTest() {
        // TODO: test valueType
    }

    /**
     * Test the property 'productSpecCharRelationship'
     */
    @Test
    public void productSpecCharRelationshipTest() {
        // TODO: test productSpecCharRelationship
    }

    /**
     * Test the property 'productSpecCharacteristicValue'
     */
    @Test
    public void productSpecCharacteristicValueTest() {
        // TODO: test productSpecCharacteristicValue
    }

    /**
     * Test the property 'validFor'
     */
    @Test
    public void validForTest() {
        // TODO: test validFor
    }

    /**
     * Test the property 'atBaseType'
     */
    @Test
    public void atBaseTypeTest() {
        // TODO: test atBaseType
    }

    /**
     * Test the property 'atSchemaLocation'
     */
    @Test
    public void atSchemaLocationTest() {
        // TODO: test atSchemaLocation
    }

    /**
     * Test the property 'atType'
     */
    @Test
    public void atTypeTest() {
        // TODO: test atType
    }

}
