/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.ProductSpecification;

/**
 * The event data structure
 */
@ApiModel(description = "The event data structure")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-10-08T14:44:14.902+13:00[Pacific/Auckland]")
public class ProductSpecificationDeleteEventPayload {
  public static final String SERIALIZED_NAME_PRODUCT_SPECIFICATION = "productSpecification";
  @SerializedName(SERIALIZED_NAME_PRODUCT_SPECIFICATION)
  private ProductSpecification productSpecification;


  public ProductSpecificationDeleteEventPayload productSpecification(ProductSpecification productSpecification) {
    
    this.productSpecification = productSpecification;
    return this;
  }

   /**
   * Get productSpecification
   * @return productSpecification
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public ProductSpecification getProductSpecification() {
    return productSpecification;
  }


  public void setProductSpecification(ProductSpecification productSpecification) {
    this.productSpecification = productSpecification;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ProductSpecificationDeleteEventPayload productSpecificationDeleteEventPayload = (ProductSpecificationDeleteEventPayload) o;
    return Objects.equals(this.productSpecification, productSpecificationDeleteEventPayload.productSpecification);
  }

  @Override
  public int hashCode() {
    return Objects.hash(productSpecification);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ProductSpecificationDeleteEventPayload {\n");
    sb.append("    productSpecification: ").append(toIndentedString(productSpecification)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

