/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ProductOffering;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductOfferingApi
 */
@Ignore
public class ProductOfferingApiTest {

    private final ProductOfferingApi api = new ProductOfferingApi();

    
    /**
     * List or find ProductOffering objects
     *
     * This operation list or find ProductOffering entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProductOfferingTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<ProductOffering> response = api.listProductOffering(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Retrieves a ProductOffering by ID
     *
     * This operation retrieves a ProductOffering entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveProductOfferingTest() throws ApiException {
        String id = null;
        String fields = null;
        ProductOffering response = api.retrieveProductOffering(id, fields);

        // TODO: test validations
    }
    
}
