/*
 * CoalFired product catalog
 * This API contains a catalog of CoalFired's products and pricing
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support+coalfired@practiv.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.api;

import org.openapitools.client.ApiException;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ProductOfferingPrice;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ProductOfferingPriceApi
 */
@Ignore
public class ProductOfferingPriceApiTest {

    private final ProductOfferingPriceApi api = new ProductOfferingPriceApi();

    
    /**
     * List or find ProductOfferingPrice objects
     *
     * This operation list or find ProductOfferingPrice entities
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void listProductOfferingPriceTest() throws ApiException {
        String fields = null;
        Integer offset = null;
        Integer limit = null;
        List<ProductOfferingPrice> response = api.listProductOfferingPrice(fields, offset, limit);

        // TODO: test validations
    }
    
    /**
     * Retrieves a ProductOfferingPrice by ID
     *
     * This operation retrieves a ProductOfferingPrice entity. Attribute selection is enabled for all first level attributes.
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void retrieveProductOfferingPriceTest() throws ApiException {
        String id = null;
        String fields = null;
        ProductOfferingPrice response = api.retrieveProductOfferingPrice(id, fields);

        // TODO: test validations
    }
    
}
